SELECT nombre FROM Producto;
SELECT nombre, precio FROM Producto;
SELECT * FROM Producto;
SELECT nombre, precio, precio*1.13 FROM Producto;
SELECT nombre AS "nom de producto", precio AS "euros", precio*1.13 AS "dolars" FROM Producto;
SELECT upper(nombre) FROM Producto;
SELECT lower(nombre) FROM Producto;
SELECT nombre, left(upper(nombre), 2) FROM Fabricante;
SELECT nombre, round(precio) FROM Producto;
SELECT nombre, truncate(precio, 0) FROM Producto;
SELECT Fabricante.codigo, Producto.codigo_fabricante FROM Fabricante INNER JOIN Producto ON Fabricante.codigo = Producto.codigo_fabricante;
SELECT distinct Fabricante.codigo, Producto.codigo_fabricante FROM Fabricante INNER JOIN Producto ON Fabricante.codigo = Producto.codigo_fabricante;
SELECT nombre FROM Fabricante ORDER BY nombre ASC;
SELECT nombre FROM Fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM Producto ORDER BY nombre ASC; SELECT nombre, precio FROM Producto ORDER BY precio DESC;
SELECT * FROM Fabricante LIMIT 0, 5;
SELECT * FROM Fabricante LIMIT 3, 2;
SELECT nombre, precio FROM Producto ORDER BY Precio ASC LIMIT 0,1;
SELECT nombre, precio FROM Producto ORDER BY Precio DESC LIMIT 0,1;
SELECT nombre FROM Producto WHERE codigo_fabricante=2;
SELECT Fabricante.nombre, Producto.precio, Producto.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante;
SELECT Fabricante.nombre, Producto.precio, Producto.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante ORDER BY Fabricante.nombre ASC;
SELECT Producto.codigo, Producto.nombre, Fabricante.codigo, Fabricante.nombre FROM Fabricante, Producto;
SELECT Producto.nombre, Producto.precio, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante WHERE precio=(SELECT min(precio) FROM Producto);
SELECT Producto.nombre, Producto.precio, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante WHERE precio=(SELECT max(precio) FROM Producto);
SELECT * FROM Producto, Fabricante WHERE Fabricante.nombre="Lenovo";
SELECT * FROM Producto, Fabricante WHERE Fabricante.nombre="Crucial" AND precio>"200";
SELECT * FROM Producto, Fabricante WHERE Fabricante.nombre="Crucial" OR Fabricante.nombre="Hewlett-Packard" OR Fabricante.nombre="Seagate";
SELECT * FROM Producto, Fabricante WHERE Fabricante.nombre IN ("Crucial", "Hewlett-Packard", "Seagate");
SELECT Producto.nombre, Producto.precio, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo WHERE Fabricante.nombre LIKE "%e";
SELECT Producto.nombre, Producto.precio, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo WHERE Fabricante.nombre LIKE "%w%";
SELECT Producto.nombre, Producto.precio, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante WHERE Producto.precio >="180" ORDER BY Producto.precio DESC; SELECT Producto.nombre, Producto.precio, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo WHERE Producto.precio >="180" ORDER BY Producto.nombre ASC;
SELECT Fabricante.codigo, Fabricante.nombre FROM Fabricante INNER JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante;
SELECT Fabricante.nombre, Producto.nombre FROM Fabricante LEFT JOIN Producto ON Fabricante.codigo=Producto.codigo_fabricante;
SELECT nombre FROM Fabricante WHERE codigo NOT IN (select codigo_fabricante FROM Producto);
SELECT Producto.nombre FROM Producto LEFT JOIN Fabricante ON Fabricante.codigo=Producto.codigo_fabricante WHERE Fabricante.nombre = "Lenovo";
SELECT * FROM Producto RIGHT JOIN Fabricante ON Fabricante.codigo= Producto.codigo_fabricante WHERE Producto.precio=(SELECT max(precio)) AND Fabricante.nombre="Lenovo";
SELECT Producto.nombre FROM Producto INNER JOIN Fabricante ON Fabricante.codigo=Producto.codigo_fabricante WHERE Producto.precio=(SELECT max(Producto.precio)) AND Fabricante.nombre="Lenovo";
SELECT Producto.nombre FROM Producto INNER JOIN Fabricante ON Fabricante.codigo=Producto.codigo_fabricante WHERE Producto.precio=(SELECT min(Producto.precio)) AND Fabricante.nombre="Lenovo";
SELECT Producto.nombre FROM Producto INNER JOIN Fabricante ON Fabricante.codigo= Producto.codigo_fabricante WHERE Producto.precio>=(SELECT max(Producto.precio)) AND Fabricante.nombre="Lenovo";
SELECT Producto.nombre FROM Producto INNER JOIN Fabricante ON Fabricante.codigo= Producto.codigo_fabricante WHERE Producto.precio>(SELECT avg(Producto.precio)) AND Fabricante.nombre="Asus";
