/*
-- Query: SELECT * FROM JocDeDaus.partides
LIMIT 0, 1000

-- Date: 2022-04-17 10:33
*/
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (1,2,5,'1',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (2,5,6,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (3,6,5,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (4,5,6,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (5,4,1,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (6,6,3,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (7,1,1,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (8,5,5,'0',1);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (9,4,1,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (10,1,5,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (11,6,1,'1',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (12,4,3,'1',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (13,4,3,'1',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (14,1,4,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (15,4,4,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (16,2,6,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (17,4,1,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (18,4,1,'0',2);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (19,2,3,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (20,2,4,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (21,5,5,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (22,1,6,'1',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (23,5,5,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (24,1,3,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (25,5,5,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (26,5,4,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (27,4,4,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (28,3,6,'0',3);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (29,2,6,'0',4);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (30,4,2,'0',4);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (31,1,1,'0',4);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (32,6,1,'1',4);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (33,1,5,'0',4);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (34,3,4,'1',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (35,1,3,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (36,4,5,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (37,6,5,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (38,1,6,'1',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (39,5,5,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (40,2,1,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (41,3,1,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (42,4,1,'0',5);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (43,2,1,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (44,3,3,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (45,2,1,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (46,1,4,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (47,3,5,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (48,6,2,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (49,3,1,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (50,1,2,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (51,3,1,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (52,2,4,'0',6);
INSERT INTO `` (`partida_id`,`dau_1`,`dau_2`,`winner`,`jugador_id`) VALUES (53,5,6,'0',6);
