/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springBootInitialDemo;

import org.springframework.boot.SpringApplication;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.PathVariable;
//import org.springframework.web.bind.annotation.RequestParam;
//import springBootInitialDemo.controller.InitialController;
//import org.springframework.web.bind.annotation.GetMapping;
//import org.springframework.web.bind.annotation.RestController;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
//@RestController
public class App {

	public static void main(String[] args) {

		SpringApplication.run(App.class, args);
	}
	
}
